### PR TITLE
update recipe to 0.9.12

### PR DESCRIPTION
**Pull request by newville**
this updates the conda-forge recipe for asteval to version 0.9.12

### CODE REVIEW

**Comment by newville** [comment]
this is a pure python package that depends on `six`, `numpy`, and `setuptools`.  It definitely passes all tests for Py27, Py35, and Py36.   I re-rendered the recipe here with the latest conda-smithy.   Tests pass everywhere except Appveyor, which gives an error message of

    'conda.exe' is not recognized as an internal or external command, operable program or batch file. 
    Command exited with code 1

The appveyor recipe is the standard conda-forge recipe.  It's hard to see how this is anything other than a problem with conda-forge recipes.  

Please either fix the tools so that appveyor works or remove this recipe and the conda-forge package for asteval entirely.  The current  package is out-of-date.

**Comment by CJ-Wright** [comment]
I'm fairly confident that we can work out the issues.

Would you mind changing the build script over to pip? https://conda-forge.org/docs/meta.html#use-pip
Would you be interested in being a package maintainer?
Would you mind adding noarch to this package?

**Comment by newville** [comment]
> Would you mind changing the build script over to pip? https://conda-forge.org/docs/meta.html#use-pip

Why?  What does that accomplish?

> Would you be interested in being a package maintainer?

Maybe.  I need convincing that this is worthwhile. I'm sort of not exactly a strong advocate of conda-forge.  I avoid it like the plague. It does  insane things like overwrite python.   But if there is going to be a conda-forge, and needs to have `lmfit` (apparently it does....) then that needs an up-to-date `asteval` that has to build inside the rules conda-forge made up for itself.  


>  Would you mind adding noarch to this package and rerendering with the latest stable release of conda-simthy?

Why? Really, this is an incredibly simple packaging problem.  It is pure python, needing exactly and only `setuptools`, `six`, and `numpy` -- all core conda packages.  The code absolutely passes all tests on all platforms.  Why is this recipe evenly remotely hard?  Why does it require any discussion at all?  Yes, I really want answers to these questions.   Conda-forge seems very, very broken to me, and your asking me to play by its rules and tweak build scripts that most certainly work.

**Comment by CJ-Wright** [comment]
1. The pip based build script work better with noarch (see below)
1. This is the second time that a package has gone out of date and that you have put in a PR to bring it into date, at least as a maintainer you would have the privileges to merge your own PRs and otherwise manage the feedstock better. (We appreciate maintainers being passionate about making sure that the packages we put out are the best they can be!)
    1. I'm not certain what you mean by overwrite python, but if there is a specific issue that you have caused by conda-forge, please let us know!
    1. Have you by any chance read [this](http://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/)? While it might not be perfect, it does give a good primer on why conda exists, and to some extent why conda-forge exists.
1. `noarch: python` is designed to make the build setup simpler for python only packages. `noarch` packages only need to build on circleci (linux) and it is good for the other OSes. This would essentially make any issues on OSX(travis) or Windows(appveyor) moot. I believe that this would fix the problem you are currently experiencing. Additionally it would also help reduce the load on the CIs building the code, which is good for everyone!
    1. As for why this was particularly hard and requires discussion, I think (although don't know for certain) that part of this is due to the use of a unreleased version of `conda-smithy` to rerender the package which I believe is currently discouraged unless one is willing to troubleshoot the accompanying issues. I attempted to mitigate this issue by asking our admin bot to rerender the feedstock, which hopefully will fix the problem (although if the package goes `noarch` then this is all moot since we won't need to wait for the appveyor build to finish).
1. I'd be happy to try address the issues you are having, although this PR might not be the best place. Would you mind opening issues not specific to this feedstock at https://github.com/conda-forge/conda-forge.github.io?

Next time you need help with this kind of issue I'd suggest to contact the core devs via @conda-forge/core.

**Comment by CJ-Wright** [comment]
@conda-forge/asteval please review and/or merge
Also please try to make this a noarch package at your earliest convenience.

I suspect that the use of unreleased code most likely caused the issue in the first place, @newville next time please make a point to use the stable, released `conda smithy` code to rerender feedstocks, or to use the webservice call that I made previously. Did you follow the docs on how to rerender feedstocks, and obtain and use [conda-smithy](https://conda-forge.org/docs/conda_smithy.html#how-to-re-render)?

**Comment by souravsingh** [comment]
About the version bump, I didn't notice the PR sent by the conda-forge admin for rerender and the regro auto-tick for the version bump. So I can take the blame for it.

**Comment by jakirkham** [comment]
Pushed a commit to clean out some lingering CI files from the dev version of conda-smithy.

**Comment by souravsingh** [comment]
Merging

**Comment by souravsingh** [comment]
@newville The new version of `asteval` is now available here- https://anaconda.org/conda-forge/asteval/files

**Comment by newville** [comment]
@CJ-Wright @jakirkham @souravsingh  Thanks for fixing the recipe.  Looks to me like conda-smithy master has broken appveyor scripts.  

I'm OK with being a maintainer of the asteval recipe for conda-forge.  I have read the motivation for conda, and have no objections to using conda  -- I keep my own channel,  including for asteval.   But conda-forge is one channel, and the source of many headaches.

Note that the advice and solution were to use `noarch` or to remove the appveyor script.  But of these are *aimed at* disabling conda-forges automated testing because this automated testing is broken by conda-forge's auto-generated scripts.   The problem is *not* with the package or with appveyor.  It is with conda-forge.

**Comment by jakirkham** [comment]
It would be great to hear more about your concerns and issues with conda-forge in a fresh issue on [the webpage repo]( https://github.com/conda-forge/conda-forge.github.io ). Hope we can find suitable solutions.

Thanks for being patient with us. Periodically CIs do change their offerings both in terms of how they expect to be configured (e.g. CircleCI in this case) and what they provide on their images (e.g. AppVeyor in this case). While they are kind enough to provide these free services to us in the first place and they generally are receptive to our suggestions on how to improve things, ultimately we are not in the driver's seat when it comes to what happens on CIs. Our main form of recourse is to configure the CI scripts to stay on top of this changing environment. That is what `conda-smithy` offers us in this case. Periodically we do have to change the templates in this tool to handle changes our service providers make. Though this is to be expected. That said, we are always looking for ways to minimize this impact on our users and make it easier to stay on top of the CI changes.

We are aware that `conda-smithy`'s `master` branch has some kinks to be worked out. The AppVeyor problem in particular is a known issue ( https://github.com/conda-forge/conda-smithy/issues/713 ) with `conda-smithy`'s `master` branch (though not the stable `2.4.5` release) that recently cropped up. That said, this is why we haven't tagged a release including those changes yet. :) It's also why a tagged release of `conda-smithy` (particularly in the form of the `conda-forge` package) should be preferred. ;) Alternatively using the webservice as @CJ-Wright pointed out makes all of this trivial and the version of `conda-smithy` used irrelevant as it automates the whole process.

There seems to be a little confusion as to the motivation for suggesting `noarch`. The main point is this would make the package simpler to maintain from a maintainer perspective and also from an org-wide perspective. As you pointed out this is a simple pure Python package, in this case we really only need to build and test the package once on one CI to get a good usable package on all platforms (hence `noarch` ;). This is good for the maintainer as there are less CI issues to crop up (as occurred here) and it is good for the org as it uses a smaller amount of our collective resources (CI time, storage on Anaconda.org, etc.).

Hope that provides a little more context and info to what @CJ-Wright has already said above. Happy to answer more questions and/or discuss concerns that crop up. Thanks for helping out. :)

**Pull request merged**
