### PR TITLE
Trying with setuptools-scm instead of stetuptools

### PR DESCRIPTION
**Pull request by HeavyTony2**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by HeavyTony2** [comment]
Setuptools-scm was listed by grayskull instead of setuptools. It seems it was the issue.

**Comment by newville** [comment]
@HeavyTony2 this seems OK to me.  For sure, setuptools_scm is needed.    

The correct way to install this package is `pip install asteval`.  

Everything in this recipe other than those 19 characters is actually fluff.  It's fine with me if you or anyone else wants to spend their time on that.

**Comment by HeavyTony2** [comment]
@newville The recipe could be cleaned, however it would require to sacrifice the noarch build for anaconda because of the :
```
run:
    - importlib_metadata  # [py<38]
```
So I think the best option is to keep the fluff for now.

**Comment by newville** [comment]
@HeavyTony2 OK.  I guess I would consider that "run" paragraph as part of the fluff (that dependency is handled by pip), though I would also say that I don't know where that "run" paragraph is meant to go. 

It is sort of impressive how complex (and slow!) conda insists on making things.

**Comment by HeavyTony2** [comment]
@newville  Nevermind, I've been able to clean the recipe. I just had to replace the  " - importlib_metadata  # [py<38]" by "pip". It's now structured accorded to nowaday standards. Also, it doesn't skip the dependancies check anymore. You can merge the PR if you want.

Conda is a very intriguing world.

**Pull request merged**
